"""
Build plots, GIFs and results/RESULTS.md from the runs in results/runs/.

Usage:
    python scripts/make_report.py            # plots + table + GIFs
    python scripts/make_report.py --no-gifs  # skip rendering
"""
import argparse
import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import gymnasium as gym

from scripts.train import ENVS, build_agent
from src.environments.utils import get_env_dims
from src.evaluation.plotting import plot_seeds_by_steps
from src.evaluation.recording import record_episode

ROOT = Path(__file__).parent.parent
RESULTS = ROOT / "results"
ALGO_NAMES = {"dqn": "DQN", "ppo": "PPO"}


def load_runs(runs_dir: Path) -> dict:
    grouped: defaultdict[str, defaultdict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    for path in sorted(runs_dir.glob("*.json")):
        run = json.loads(path.read_text(encoding="utf-8"))
        grouped[run["env"]][run["algo"]].append(run)
    return grouped


def fmt_steps(n) -> str:
    return f"{n / 1000:.0f}k" if n is not None else "—"


def summary_row(env: str, algo: str, runs: list) -> str:
    solved = [r["solved_at_step"] for r in runs if r["solved_at_step"] is not None]
    evals = [r["evaluation"]["mean_reward"] for r in runs]
    sampled = [r["evaluation_sampled"]["mean_reward"] for r in runs if r.get("evaluation_sampled")]
    median_solve = fmt_steps(statistics.median(solved)) if solved else "—"
    return (
        f"| {ENVS[env][0]} | {ALGO_NAMES[algo]} | {len(solved)}/{len(runs)} | {median_solve} | "
        f"{mean_sd(evals)} | {mean_sd(sampled) if sampled else '—'} |"
    )


def mean_sd(values: list) -> str:
    spread = f" ± {statistics.stdev(values):.1f}" if len(values) > 1 else ""
    return f"{statistics.mean(values):.1f}{spread}"


def best_mode(run: dict) -> tuple[float, bool]:
    """(score, deterministic) for the better of the run's greedy and sampled evaluations."""
    modes = [(run["evaluation"]["mean_reward"], True)]
    if run.get("evaluation_sampled"):
        modes.append((run["evaluation_sampled"]["mean_reward"], False))
    return max(modes)


def best_run(runs: list) -> dict:
    return max(runs, key=lambda r: best_mode(r)[0])


def render_gif(run: dict, path: Path) -> float:
    env = gym.make(run["env_id"])
    obs_dim, action_dim = get_env_dims(env)
    env.close()
    agent = build_agent(run["algo"], obs_dim, action_dim, run["hyperparams"])
    agent.load(RESULTS / "models" / f"{run['algo']}_{run['env']}_seed{run['seed']}.pt")
    return record_episode(agent, run["env_id"], path, seed=run["seed"], deterministic=best_mode(run)[1])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-gifs", action="store_true")
    args = parser.parse_args()

    grouped = load_runs(RESULTS / "runs")
    if not grouped:
        sys.exit("no runs in results/runs — train first with scripts/train.py")

    lines = [
        "# Results",
        "",
        "Generated by `scripts/make_report.py` from `results/runs/*.json`.",
        "",
        "- **Solved**: seeds whose trailing 100-episode training return reached the threshold "
        "(CartPole 475, LunarLander 200). Training stops there.",
        "- **Greedy eval**: mean return of the final policy over 100 fresh episodes, always "
        "taking the highest-valued / most likely action. The ± is the spread across seeds.",
        "- **Sampled eval** (PPO only): the same, but sampling actions from the learned policy "
        "distribution, which is how PPO is trained and acts.",
        "",
        "| Environment | Algorithm | Solved | Median steps to solve | Greedy eval | Sampled eval |",
        "| :--- | :--- | :---: | ---: | ---: | ---: |",
    ]
    for env in ENVS:
        for algo in ALGO_NAMES:
            if grouped[env][algo]:
                lines.append(summary_row(env, algo, grouped[env][algo]))

    lines += [
        "",
        "## Per seed",
        "",
        "| Run | Steps trained | Solved at | Greedy eval | Sampled eval |",
        "| :--- | ---: | ---: | ---: | ---: |",
    ]
    for env in ENVS:
        for algo in ALGO_NAMES:
            for r in sorted(grouped[env][algo], key=lambda r: r["seed"]):
                ev, sp = r["evaluation"], r.get("evaluation_sampled")
                sampled = f"{sp['mean_reward']:.1f} ± {sp['std_reward']:.1f}" if sp else "—"
                lines.append(
                    f"| {algo}_{env}_seed{r['seed']} | {r['total_steps']:,} | "
                    f"{fmt_steps(r['solved_at_step'])} | {ev['mean_reward']:.1f} ± {ev['std_reward']:.1f} | {sampled} |"
                )

    for env, (env_id, threshold) in ENVS.items():
        by_algo = {
            ALGO_NAMES[a]: [(r["episode_steps"], r["episode_rewards"]) for r in grouped[env][a]]
            for a in ALGO_NAMES
            if grouped[env][a]
        }
        if by_algo:
            plot_seeds_by_steps(
                by_algo,
                title=f"DQN vs PPO — {env_id}",
                threshold=threshold,
                save_path=RESULTS / "plots" / f"{env}_dqn_vs_ppo.png",
            )

        if not args.no_gifs:
            for algo in ALGO_NAMES:
                if grouped[env][algo]:
                    run = best_run(grouped[env][algo])
                    ret = render_gif(run, RESULTS / "gifs" / f"{algo}_{env}.gif")
                    mode = "greedy" if best_mode(run)[1] else "sampled"
                    print(f"GIF {algo}_{env} (seed {run['seed']}, {mode}): return {ret:.1f}")

    (RESULTS / "RESULTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {RESULTS / 'RESULTS.md'}")


if __name__ == "__main__":
    main()
