"""
How well do the trained agents cope with noisy sensors?

Evaluates every saved model in results/models/ with Gaussian noise added to its
observations. Noise is scaled per dimension by the standard deviation of that
dimension in clean episodes (pooled over all models of the environment), so
"0.2" means "20% of the typical spread of each reading" for both environments.

Writes results/robustness.json, results/ROBUSTNESS.md and
results/plots/robustness.png.

Usage:
    python scripts/robustness.py                # 30 episodes per level
    python scripts/robustness.py --episodes 10  # quicker
"""
import argparse
import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import gymnasium as gym
import numpy as np
import torch

from scripts.train import ENVS, build_agent
from src.environments.utils import get_env_dims
from src.environments.wrappers import GaussianObservationNoise
from src.evaluation.plotting import plot_noise_robustness

ROOT = Path(__file__).parent.parent
RESULTS = ROOT / "results"
NOISE_LEVELS = [0.0, 0.05, 0.1, 0.2, 0.5, 1.0]
ALGO_NAMES = {"dqn": "DQN", "ppo": "PPO"}


def load_agent(run: dict):
    env = gym.make(run["env_id"])
    obs_dim, action_dim = get_env_dims(env)
    env.close()
    agent = build_agent(run["algo"], obs_dim, action_dim, run["hyperparams"])
    agent.load(RESULTS / "models" / f"{run['algo']}_{run['env']}_seed{run['seed']}.pt")
    return agent


def play(agent, env: gym.Env, episodes: int, seed: int, record: list | None = None) -> list[float]:
    """Greedy returns over `episodes` episodes; optionally collects the observations seen."""
    returns = []
    for ep in range(episodes):
        obs, _ = env.reset(seed=seed + ep)
        done, total = False, 0.0
        while not done:
            if record is not None:
                record.append(obs)
            obs, reward, terminated, truncated, _ = env.step(agent.act(obs, training=False))
            total += float(reward)
            done = terminated or truncated
        returns.append(total)
    return returns


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--episodes", type=int, default=30)
    args = parser.parse_args()
    torch.set_num_threads(1)

    runs = [json.loads(p.read_text(encoding="utf-8")) for p in sorted((RESULTS / "runs").glob("*.json"))]
    runs = [r for r in runs if (RESULTS / "models" / f"{r['algo']}_{r['env']}_seed{r['seed']}.pt").exists()]
    if not runs:
        sys.exit("no trained models in results/models — train first with scripts/train.py")

    agents = {id(r): load_agent(r) for r in runs}
    results: dict = {}
    for env_name, (env_id, threshold) in ENVS.items():
        env_runs = [r for r in runs if r["env"] == env_name]
        if not env_runs:
            continue

        # Per-dimension spread of clean observations, pooled over all models of this env.
        seen: list = []
        for r in env_runs:
            env = gym.make(env_id)
            play(agents[id(r)], env, episodes=5, seed=50_000, record=seen)
            env.close()
        scale = np.std(np.asarray(seen), axis=0)

        results[env_name] = {"env_id": env_id, "threshold": threshold, "obs_std": scale.tolist(), "runs": []}
        for r in env_runs:
            by_level = []
            for level in NOISE_LEVELS:
                env = GaussianObservationNoise(gym.make(env_id), sigma=level * scale, seed=r["seed"])
                returns = play(agents[id(r)], env, args.episodes, seed=100_000)
                env.close()
                by_level.append(statistics.mean(returns))
            results[env_name]["runs"].append({"algo": r["algo"], "seed": r["seed"], "mean_return": by_level})
            print(f"{r['algo']}/{env_name}/seed{r['seed']}: " + "  ".join(f"{l:g}sd:{v:.0f}" for l, v in zip(NOISE_LEVELS, by_level)))

    payload = {"noise_levels": NOISE_LEVELS, "episodes": args.episodes, "policy": "greedy", "envs": results}
    (RESULTS / "robustness.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    write_markdown(payload)
    plot_noise_robustness(payload, ALGO_NAMES, save_path=RESULTS / "plots" / "robustness.png")
    print(f"wrote {RESULTS / 'ROBUSTNESS.md'} and results/plots/robustness.png")


def write_markdown(payload: dict) -> None:
    levels = payload["noise_levels"]
    lines = [
        "# Robustness to observation noise",
        "",
        "Generated by `scripts/robustness.py`. Gaussian noise is added to every observation; "
        "its standard deviation is the given multiple of each dimension's spread in clean episodes. "
        f"Greedy policy, {payload['episodes']} episodes per level, mean over seeds (range in brackets).",
        "",
        "| Environment | Algorithm | " + " | ".join(f"{l:g}σ" for l in levels) + " |",
        "| :--- | :--- | " + " | ".join("---:" for _ in levels) + " |",
    ]
    for env_name, env in payload["envs"].items():
        by_algo = defaultdict(list)
        for r in env["runs"]:
            by_algo[r["algo"]].append(r["mean_return"])
        for algo, seeds in by_algo.items():
            cells = []
            for i in range(len(levels)):
                vals = [s[i] for s in seeds]
                cells.append(f"{statistics.mean(vals):.0f} [{min(vals):.0f}…{max(vals):.0f}]")
            lines.append(f"| {env['env_id']} | {ALGO_NAMES[algo]} | " + " | ".join(cells) + " |")
    (RESULTS / "ROBUSTNESS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
